### ISSUE TITLE
Snyk question

### ISSUE THREAD

**Issue by DawidJanczak** [NoRedInk/find-elm-dependencies#22]
Hello!

Question. I'm wondering if this library really need `snyk` set up in `dependencies`. That single dependency adds a ridiculous number of of its own dependencies. Our `yarn.lock` before this change weighs 273K, with `snyk` added recently that increases to 377K and that's almost 40% increase in size of an already big set of dependencies.

With dependabot PRing security changes it seems rather unnecessary. Also (if I understand this correctly) the only vulnerability it patched (SNYK-JS-LODASH-567746) is for an older version that's not used in this project anymore.

**Comment by DawidJanczak** [comment]
@lukewestby again apologies for `@` bomb, but could you have a look at this please?

**Comment by lukewestby** [comment]
@DawidJanczak sorry, snyk is a part of our company-wide process. I'll bring this up the next chance I get with all the stakeholders but for now it will stay.
