### ISSUE TITLE
Expose a function that locates the elm-package.json

### ISSUE THREAD

**Issue by gampleman** [NoRedInk/find-elm-dependencies#4]
While the logic to find the elm-package.json isn't complicated, it would be nice to not have to reimplement it in other tools that already depend on this module.

**Comment by eeue56** [comment]
This tool isn't designed for finding elm package files. It is for generating a list of imports from a given file. That's all it does. It used to live in the node-elm-compiler.

**Comment by gampleman** [comment]
Makes sense, but perhaps that would be a sensible extraction as well.
